/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as jgRouteRouteImport } from './routes/(jg)/route'
import { Route as jgIndexRouteImport } from './routes/(jg)/index'
import { Route as HotRegisterRouteImport } from './routes/hot/register'
import { Route as HotLoginRouteImport } from './routes/hot/login'
import { Route as jgAboutRouteImport } from './routes/(jg)/about'
import { Route as HotDashboardRouteRouteImport } from './routes/hot/dashboard/route'
import { Route as HotDashboardIndexRouteImport } from './routes/hot/dashboard/index'
import { Route as HotDashboardTestimoniesRouteImport } from './routes/hot/dashboard/testimonies'
import { Route as HotDashboardSermonManagerRouteImport } from './routes/hot/dashboard/sermon-manager'
import { Route as HotDashboardPrayerRequestsRouteImport } from './routes/hot/dashboard/prayer-requests'
import { Route as HotDashboardHotManagementRouteImport } from './routes/hot/dashboard/hot-management'
import { Route as HotDashboardAnnouncementsRouteImport } from './routes/hot/dashboard/announcements'
import { Route as HotDashboardAllMembersRouteImport } from './routes/hot/dashboard/all-members'

const jgRouteRoute = jgRouteRouteImport.update({
  id: '/(jg)',
  getParentRoute: () => rootRouteImport,
} as any)
const jgIndexRoute = jgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => jgRouteRoute,
} as any)
const HotRegisterRoute = HotRegisterRouteImport.update({
  id: '/hot/register',
  path: '/hot/register',
  getParentRoute: () => rootRouteImport,
} as any)
const HotLoginRoute = HotLoginRouteImport.update({
  id: '/hot/login',
  path: '/hot/login',
  getParentRoute: () => rootRouteImport,
} as any)
const jgAboutRoute = jgAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => jgRouteRoute,
} as any)
const HotDashboardRouteRoute = HotDashboardRouteRouteImport.update({
  id: '/hot/dashboard',
  path: '/hot/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HotDashboardIndexRoute = HotDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HotDashboardRouteRoute,
} as any)
const HotDashboardTestimoniesRoute = HotDashboardTestimoniesRouteImport.update({
  id: '/testimonies',
  path: '/testimonies',
  getParentRoute: () => HotDashboardRouteRoute,
} as any)
const HotDashboardSermonManagerRoute =
  HotDashboardSermonManagerRouteImport.update({
    id: '/sermon-manager',
    path: '/sermon-manager',
    getParentRoute: () => HotDashboardRouteRoute,
  } as any)
const HotDashboardPrayerRequestsRoute =
  HotDashboardPrayerRequestsRouteImport.update({
    id: '/prayer-requests',
    path: '/prayer-requests',
    getParentRoute: () => HotDashboardRouteRoute,
  } as any)
const HotDashboardHotManagementRoute =
  HotDashboardHotManagementRouteImport.update({
    id: '/hot-management',
    path: '/hot-management',
    getParentRoute: () => HotDashboardRouteRoute,
  } as any)
const HotDashboardAnnouncementsRoute =
  HotDashboardAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => HotDashboardRouteRoute,
  } as any)
const HotDashboardAllMembersRoute = HotDashboardAllMembersRouteImport.update({
  id: '/all-members',
  path: '/all-members',
  getParentRoute: () => HotDashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/hot/dashboard': typeof HotDashboardRouteRouteWithChildren
  '/about': typeof jgAboutRoute
  '/hot/login': typeof HotLoginRoute
  '/hot/register': typeof HotRegisterRoute
  '/': typeof jgIndexRoute
  '/hot/dashboard/all-members': typeof HotDashboardAllMembersRoute
  '/hot/dashboard/announcements': typeof HotDashboardAnnouncementsRoute
  '/hot/dashboard/hot-management': typeof HotDashboardHotManagementRoute
  '/hot/dashboard/prayer-requests': typeof HotDashboardPrayerRequestsRoute
  '/hot/dashboard/sermon-manager': typeof HotDashboardSermonManagerRoute
  '/hot/dashboard/testimonies': typeof HotDashboardTestimoniesRoute
  '/hot/dashboard/': typeof HotDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof jgAboutRoute
  '/hot/login': typeof HotLoginRoute
  '/hot/register': typeof HotRegisterRoute
  '/': typeof jgIndexRoute
  '/hot/dashboard/all-members': typeof HotDashboardAllMembersRoute
  '/hot/dashboard/announcements': typeof HotDashboardAnnouncementsRoute
  '/hot/dashboard/hot-management': typeof HotDashboardHotManagementRoute
  '/hot/dashboard/prayer-requests': typeof HotDashboardPrayerRequestsRoute
  '/hot/dashboard/sermon-manager': typeof HotDashboardSermonManagerRoute
  '/hot/dashboard/testimonies': typeof HotDashboardTestimoniesRoute
  '/hot/dashboard': typeof HotDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(jg)': typeof jgRouteRouteWithChildren
  '/hot/dashboard': typeof HotDashboardRouteRouteWithChildren
  '/(jg)/about': typeof jgAboutRoute
  '/hot/login': typeof HotLoginRoute
  '/hot/register': typeof HotRegisterRoute
  '/(jg)/': typeof jgIndexRoute
  '/hot/dashboard/all-members': typeof HotDashboardAllMembersRoute
  '/hot/dashboard/announcements': typeof HotDashboardAnnouncementsRoute
  '/hot/dashboard/hot-management': typeof HotDashboardHotManagementRoute
  '/hot/dashboard/prayer-requests': typeof HotDashboardPrayerRequestsRoute
  '/hot/dashboard/sermon-manager': typeof HotDashboardSermonManagerRoute
  '/hot/dashboard/testimonies': typeof HotDashboardTestimoniesRoute
  '/hot/dashboard/': typeof HotDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/hot/dashboard'
    | '/about'
    | '/hot/login'
    | '/hot/register'
    | '/'
    | '/hot/dashboard/all-members'
    | '/hot/dashboard/announcements'
    | '/hot/dashboard/hot-management'
    | '/hot/dashboard/prayer-requests'
    | '/hot/dashboard/sermon-manager'
    | '/hot/dashboard/testimonies'
    | '/hot/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/hot/login'
    | '/hot/register'
    | '/'
    | '/hot/dashboard/all-members'
    | '/hot/dashboard/announcements'
    | '/hot/dashboard/hot-management'
    | '/hot/dashboard/prayer-requests'
    | '/hot/dashboard/sermon-manager'
    | '/hot/dashboard/testimonies'
    | '/hot/dashboard'
  id:
    | '__root__'
    | '/(jg)'
    | '/hot/dashboard'
    | '/(jg)/about'
    | '/hot/login'
    | '/hot/register'
    | '/(jg)/'
    | '/hot/dashboard/all-members'
    | '/hot/dashboard/announcements'
    | '/hot/dashboard/hot-management'
    | '/hot/dashboard/prayer-requests'
    | '/hot/dashboard/sermon-manager'
    | '/hot/dashboard/testimonies'
    | '/hot/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  jgRouteRoute: typeof jgRouteRouteWithChildren
  HotDashboardRouteRoute: typeof HotDashboardRouteRouteWithChildren
  HotLoginRoute: typeof HotLoginRoute
  HotRegisterRoute: typeof HotRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(jg)': {
      id: '/(jg)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof jgRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(jg)/': {
      id: '/(jg)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof jgIndexRouteImport
      parentRoute: typeof jgRouteRoute
    }
    '/hot/register': {
      id: '/hot/register'
      path: '/hot/register'
      fullPath: '/hot/register'
      preLoaderRoute: typeof HotRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hot/login': {
      id: '/hot/login'
      path: '/hot/login'
      fullPath: '/hot/login'
      preLoaderRoute: typeof HotLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(jg)/about': {
      id: '/(jg)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof jgAboutRouteImport
      parentRoute: typeof jgRouteRoute
    }
    '/hot/dashboard': {
      id: '/hot/dashboard'
      path: '/hot/dashboard'
      fullPath: '/hot/dashboard'
      preLoaderRoute: typeof HotDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hot/dashboard/': {
      id: '/hot/dashboard/'
      path: '/'
      fullPath: '/hot/dashboard/'
      preLoaderRoute: typeof HotDashboardIndexRouteImport
      parentRoute: typeof HotDashboardRouteRoute
    }
    '/hot/dashboard/testimonies': {
      id: '/hot/dashboard/testimonies'
      path: '/testimonies'
      fullPath: '/hot/dashboard/testimonies'
      preLoaderRoute: typeof HotDashboardTestimoniesRouteImport
      parentRoute: typeof HotDashboardRouteRoute
    }
    '/hot/dashboard/sermon-manager': {
      id: '/hot/dashboard/sermon-manager'
      path: '/sermon-manager'
      fullPath: '/hot/dashboard/sermon-manager'
      preLoaderRoute: typeof HotDashboardSermonManagerRouteImport
      parentRoute: typeof HotDashboardRouteRoute
    }
    '/hot/dashboard/prayer-requests': {
      id: '/hot/dashboard/prayer-requests'
      path: '/prayer-requests'
      fullPath: '/hot/dashboard/prayer-requests'
      preLoaderRoute: typeof HotDashboardPrayerRequestsRouteImport
      parentRoute: typeof HotDashboardRouteRoute
    }
    '/hot/dashboard/hot-management': {
      id: '/hot/dashboard/hot-management'
      path: '/hot-management'
      fullPath: '/hot/dashboard/hot-management'
      preLoaderRoute: typeof HotDashboardHotManagementRouteImport
      parentRoute: typeof HotDashboardRouteRoute
    }
    '/hot/dashboard/announcements': {
      id: '/hot/dashboard/announcements'
      path: '/announcements'
      fullPath: '/hot/dashboard/announcements'
      preLoaderRoute: typeof HotDashboardAnnouncementsRouteImport
      parentRoute: typeof HotDashboardRouteRoute
    }
    '/hot/dashboard/all-members': {
      id: '/hot/dashboard/all-members'
      path: '/all-members'
      fullPath: '/hot/dashboard/all-members'
      preLoaderRoute: typeof HotDashboardAllMembersRouteImport
      parentRoute: typeof HotDashboardRouteRoute
    }
  }
}

interface jgRouteRouteChildren {
  jgAboutRoute: typeof jgAboutRoute
  jgIndexRoute: typeof jgIndexRoute
}

const jgRouteRouteChildren: jgRouteRouteChildren = {
  jgAboutRoute: jgAboutRoute,
  jgIndexRoute: jgIndexRoute,
}

const jgRouteRouteWithChildren =
  jgRouteRoute._addFileChildren(jgRouteRouteChildren)

interface HotDashboardRouteRouteChildren {
  HotDashboardAllMembersRoute: typeof HotDashboardAllMembersRoute
  HotDashboardAnnouncementsRoute: typeof HotDashboardAnnouncementsRoute
  HotDashboardHotManagementRoute: typeof HotDashboardHotManagementRoute
  HotDashboardPrayerRequestsRoute: typeof HotDashboardPrayerRequestsRoute
  HotDashboardSermonManagerRoute: typeof HotDashboardSermonManagerRoute
  HotDashboardTestimoniesRoute: typeof HotDashboardTestimoniesRoute
  HotDashboardIndexRoute: typeof HotDashboardIndexRoute
}

const HotDashboardRouteRouteChildren: HotDashboardRouteRouteChildren = {
  HotDashboardAllMembersRoute: HotDashboardAllMembersRoute,
  HotDashboardAnnouncementsRoute: HotDashboardAnnouncementsRoute,
  HotDashboardHotManagementRoute: HotDashboardHotManagementRoute,
  HotDashboardPrayerRequestsRoute: HotDashboardPrayerRequestsRoute,
  HotDashboardSermonManagerRoute: HotDashboardSermonManagerRoute,
  HotDashboardTestimoniesRoute: HotDashboardTestimoniesRoute,
  HotDashboardIndexRoute: HotDashboardIndexRoute,
}

const HotDashboardRouteRouteWithChildren =
  HotDashboardRouteRoute._addFileChildren(HotDashboardRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  jgRouteRoute: jgRouteRouteWithChildren,
  HotDashboardRouteRoute: HotDashboardRouteRouteWithChildren,
  HotLoginRoute: HotLoginRoute,
  HotRegisterRoute: HotRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
