/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HotRegisterRouteImport } from './routes/hot/register'
import { Route as HotLoginRouteImport } from './routes/hot/login'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as HotDashboardRouteRouteImport } from './routes/hot/dashboard/route'
import { Route as HotDashboardIndexRouteImport } from './routes/hot/dashboard/index'
import { Route as HotDashboardTestimoniesRouteImport } from './routes/hot/dashboard/testimonies'
import { Route as HotDashboardSermonManagerRouteImport } from './routes/hot/dashboard/sermon-manager'
import { Route as HotDashboardPrayerRequestsRouteImport } from './routes/hot/dashboard/prayer-requests'
import { Route as HotDashboardHotManagementRouteImport } from './routes/hot/dashboard/hot-management'
import { Route as HotDashboardAnnouncementsRouteImport } from './routes/hot/dashboard/announcements'
import { Route as HotDashboardAllMembersRouteImport } from './routes/hot/dashboard/all-members'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoSentryTestingRouteImport } from './routes/demo/sentry.testing'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotRegisterRoute = HotRegisterRouteImport.update({
  id: '/hot/register',
  path: '/hot/register',
  getParentRoute: () => rootRouteImport,
} as any)
const HotLoginRoute = HotLoginRouteImport.update({
  id: '/hot/login',
  path: '/hot/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const HotDashboardRouteRoute = HotDashboardRouteRouteImport.update({
  id: '/hot/dashboard',
  path: '/hot/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HotDashboardIndexRoute = HotDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HotDashboardRouteRoute,
} as any)
const HotDashboardTestimoniesRoute = HotDashboardTestimoniesRouteImport.update({
  id: '/testimonies',
  path: '/testimonies',
  getParentRoute: () => HotDashboardRouteRoute,
} as any)
const HotDashboardSermonManagerRoute =
  HotDashboardSermonManagerRouteImport.update({
    id: '/sermon-manager',
    path: '/sermon-manager',
    getParentRoute: () => HotDashboardRouteRoute,
  } as any)
const HotDashboardPrayerRequestsRoute =
  HotDashboardPrayerRequestsRouteImport.update({
    id: '/prayer-requests',
    path: '/prayer-requests',
    getParentRoute: () => HotDashboardRouteRoute,
  } as any)
const HotDashboardHotManagementRoute =
  HotDashboardHotManagementRouteImport.update({
    id: '/hot-management',
    path: '/hot-management',
    getParentRoute: () => HotDashboardRouteRoute,
  } as any)
const HotDashboardAnnouncementsRoute =
  HotDashboardAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => HotDashboardRouteRoute,
  } as any)
const HotDashboardAllMembersRoute = HotDashboardAllMembersRouteImport.update({
  id: '/all-members',
  path: '/all-members',
  getParentRoute: () => HotDashboardRouteRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSentryTestingRoute = DemoSentryTestingRouteImport.update({
  id: '/demo/sentry/testing',
  path: '/demo/sentry/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hot/dashboard': typeof HotDashboardRouteRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/hot/login': typeof HotLoginRoute
  '/hot/register': typeof HotRegisterRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/hot/dashboard/all-members': typeof HotDashboardAllMembersRoute
  '/hot/dashboard/announcements': typeof HotDashboardAnnouncementsRoute
  '/hot/dashboard/hot-management': typeof HotDashboardHotManagementRoute
  '/hot/dashboard/prayer-requests': typeof HotDashboardPrayerRequestsRoute
  '/hot/dashboard/sermon-manager': typeof HotDashboardSermonManagerRoute
  '/hot/dashboard/testimonies': typeof HotDashboardTestimoniesRoute
  '/hot/dashboard/': typeof HotDashboardIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/hot/login': typeof HotLoginRoute
  '/hot/register': typeof HotRegisterRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/hot/dashboard/all-members': typeof HotDashboardAllMembersRoute
  '/hot/dashboard/announcements': typeof HotDashboardAnnouncementsRoute
  '/hot/dashboard/hot-management': typeof HotDashboardHotManagementRoute
  '/hot/dashboard/prayer-requests': typeof HotDashboardPrayerRequestsRoute
  '/hot/dashboard/sermon-manager': typeof HotDashboardSermonManagerRoute
  '/hot/dashboard/testimonies': typeof HotDashboardTestimoniesRoute
  '/hot/dashboard': typeof HotDashboardIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hot/dashboard': typeof HotDashboardRouteRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/hot/login': typeof HotLoginRoute
  '/hot/register': typeof HotRegisterRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/hot/dashboard/all-members': typeof HotDashboardAllMembersRoute
  '/hot/dashboard/announcements': typeof HotDashboardAnnouncementsRoute
  '/hot/dashboard/hot-management': typeof HotDashboardHotManagementRoute
  '/hot/dashboard/prayer-requests': typeof HotDashboardPrayerRequestsRoute
  '/hot/dashboard/sermon-manager': typeof HotDashboardSermonManagerRoute
  '/hot/dashboard/testimonies': typeof HotDashboardTestimoniesRoute
  '/hot/dashboard/': typeof HotDashboardIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hot/dashboard'
    | '/demo/tanstack-query'
    | '/hot/login'
    | '/hot/register'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/sentry/testing'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/hot/dashboard/all-members'
    | '/hot/dashboard/announcements'
    | '/hot/dashboard/hot-management'
    | '/hot/dashboard/prayer-requests'
    | '/hot/dashboard/sermon-manager'
    | '/hot/dashboard/testimonies'
    | '/hot/dashboard/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/tanstack-query'
    | '/hot/login'
    | '/hot/register'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/sentry/testing'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/hot/dashboard/all-members'
    | '/hot/dashboard/announcements'
    | '/hot/dashboard/hot-management'
    | '/hot/dashboard/prayer-requests'
    | '/hot/dashboard/sermon-manager'
    | '/hot/dashboard/testimonies'
    | '/hot/dashboard'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/hot/dashboard'
    | '/demo/tanstack-query'
    | '/hot/login'
    | '/hot/register'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/sentry/testing'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/hot/dashboard/all-members'
    | '/hot/dashboard/announcements'
    | '/hot/dashboard/hot-management'
    | '/hot/dashboard/prayer-requests'
    | '/hot/dashboard/sermon-manager'
    | '/hot/dashboard/testimonies'
    | '/hot/dashboard/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HotDashboardRouteRoute: typeof HotDashboardRouteRouteWithChildren
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  HotLoginRoute: typeof HotLoginRoute
  HotRegisterRoute: typeof HotRegisterRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoSentryTestingRoute: typeof DemoSentryTestingRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hot/register': {
      id: '/hot/register'
      path: '/hot/register'
      fullPath: '/hot/register'
      preLoaderRoute: typeof HotRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hot/login': {
      id: '/hot/login'
      path: '/hot/login'
      fullPath: '/hot/login'
      preLoaderRoute: typeof HotLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hot/dashboard': {
      id: '/hot/dashboard'
      path: '/hot/dashboard'
      fullPath: '/hot/dashboard'
      preLoaderRoute: typeof HotDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hot/dashboard/': {
      id: '/hot/dashboard/'
      path: '/'
      fullPath: '/hot/dashboard/'
      preLoaderRoute: typeof HotDashboardIndexRouteImport
      parentRoute: typeof HotDashboardRouteRoute
    }
    '/hot/dashboard/testimonies': {
      id: '/hot/dashboard/testimonies'
      path: '/testimonies'
      fullPath: '/hot/dashboard/testimonies'
      preLoaderRoute: typeof HotDashboardTestimoniesRouteImport
      parentRoute: typeof HotDashboardRouteRoute
    }
    '/hot/dashboard/sermon-manager': {
      id: '/hot/dashboard/sermon-manager'
      path: '/sermon-manager'
      fullPath: '/hot/dashboard/sermon-manager'
      preLoaderRoute: typeof HotDashboardSermonManagerRouteImport
      parentRoute: typeof HotDashboardRouteRoute
    }
    '/hot/dashboard/prayer-requests': {
      id: '/hot/dashboard/prayer-requests'
      path: '/prayer-requests'
      fullPath: '/hot/dashboard/prayer-requests'
      preLoaderRoute: typeof HotDashboardPrayerRequestsRouteImport
      parentRoute: typeof HotDashboardRouteRoute
    }
    '/hot/dashboard/hot-management': {
      id: '/hot/dashboard/hot-management'
      path: '/hot-management'
      fullPath: '/hot/dashboard/hot-management'
      preLoaderRoute: typeof HotDashboardHotManagementRouteImport
      parentRoute: typeof HotDashboardRouteRoute
    }
    '/hot/dashboard/announcements': {
      id: '/hot/dashboard/announcements'
      path: '/announcements'
      fullPath: '/hot/dashboard/announcements'
      preLoaderRoute: typeof HotDashboardAnnouncementsRouteImport
      parentRoute: typeof HotDashboardRouteRoute
    }
    '/hot/dashboard/all-members': {
      id: '/hot/dashboard/all-members'
      path: '/all-members'
      fullPath: '/hot/dashboard/all-members'
      preLoaderRoute: typeof HotDashboardAllMembersRouteImport
      parentRoute: typeof HotDashboardRouteRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/sentry/testing': {
      id: '/demo/sentry/testing'
      path: '/demo/sentry/testing'
      fullPath: '/demo/sentry/testing'
      preLoaderRoute: typeof DemoSentryTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HotDashboardRouteRouteChildren {
  HotDashboardAllMembersRoute: typeof HotDashboardAllMembersRoute
  HotDashboardAnnouncementsRoute: typeof HotDashboardAnnouncementsRoute
  HotDashboardHotManagementRoute: typeof HotDashboardHotManagementRoute
  HotDashboardPrayerRequestsRoute: typeof HotDashboardPrayerRequestsRoute
  HotDashboardSermonManagerRoute: typeof HotDashboardSermonManagerRoute
  HotDashboardTestimoniesRoute: typeof HotDashboardTestimoniesRoute
  HotDashboardIndexRoute: typeof HotDashboardIndexRoute
}

const HotDashboardRouteRouteChildren: HotDashboardRouteRouteChildren = {
  HotDashboardAllMembersRoute: HotDashboardAllMembersRoute,
  HotDashboardAnnouncementsRoute: HotDashboardAnnouncementsRoute,
  HotDashboardHotManagementRoute: HotDashboardHotManagementRoute,
  HotDashboardPrayerRequestsRoute: HotDashboardPrayerRequestsRoute,
  HotDashboardSermonManagerRoute: HotDashboardSermonManagerRoute,
  HotDashboardTestimoniesRoute: HotDashboardTestimoniesRoute,
  HotDashboardIndexRoute: HotDashboardIndexRoute,
}

const HotDashboardRouteRouteWithChildren =
  HotDashboardRouteRoute._addFileChildren(HotDashboardRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HotDashboardRouteRoute: HotDashboardRouteRouteWithChildren,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  HotLoginRoute: HotLoginRoute,
  HotRegisterRoute: HotRegisterRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoSentryTestingRoute: DemoSentryTestingRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
